"""add description to etf info

Revision ID: 74d33540b2a9
Revises: ced6121355c1
Create Date: 2026-09-02 17:21:28.431925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d33540b2a9'
down_revision: Union[str, Sequence[str], None] = 'ced6121355c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etf_info', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etf_info', 'description')
    # ### end Alembic commands ###
